SET search_path TO sharkmen;
CREATE TABLE LICENSE_PLATE
(
    ID                   INTEGER NOT NULL,
    LICENSE_PLATE_NUMBER VARCHAR(10),
    COUNTRY              VARCHAR(56),
    CONSTRAINT PK_LICENSE_PLATE PRIMARY KEY (ID)

);



CREATE TABLE MEMBER
(
    ID                  INTEGER                  NOT NULL,
    FIRSTNAME           VARCHAR(256)             NOT NULL,
    LASTNAME            VARCHAR(256)             NOT NULL,
    FK_ADDRESS_ID       INTEGER                  NOT NULL,
    PHONE_NUMBER        VARCHAR(20)              NOT NULL,
    EMAIL_ADDRESS       VARCHAR(320)             NOT NULL,
    FK_LICENSE_PLATE_ID INTEGER                  NOT NULL,
    REGISTRATION_DATE   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_MEMBER PRIMARY KEY (ID),
    CONSTRAINT FK_ADDRESS FOREIGN KEY (FK_ADDRESS_ID) REFERENCES ADDRESS (ID),
    CONSTRAINT FK_LICENSE_PLATE FOREIGN KEY (FK_LICENSE_PLATE_ID) REFERENCES LICENSE_PLATE (ID)

);



